name: matrics_gen

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - name: Metrics embed
            uses: lowlighter/metrics@latest
            with:
                filename: matrics.classic.svg
                token: ${{ secrets.MATRICS_TOKEN }}
                base: header. repositories
                plugin_lines: yes